//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445PublicLibrary.CheckoutRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckoutRef.ICheckoutService")]
    public interface ICheckoutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckoutService/CheckoutBook", ReplyAction="http://tempuri.org/ICheckoutService/CheckoutBookResponse")]
        bool CheckoutBook(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckoutService/CheckoutBook", ReplyAction="http://tempuri.org/ICheckoutService/CheckoutBookResponse")]
        System.Threading.Tasks.Task<bool> CheckoutBookAsync(string title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckoutServiceChannel : CSE445PublicLibrary.CheckoutRef.ICheckoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckoutServiceClient : System.ServiceModel.ClientBase<CSE445PublicLibrary.CheckoutRef.ICheckoutService>, CSE445PublicLibrary.CheckoutRef.ICheckoutService {
        
        public CheckoutServiceClient() {
        }
        
        public CheckoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckoutBook(string title) {
            return base.Channel.CheckoutBook(title);
        }
        
        public System.Threading.Tasks.Task<bool> CheckoutBookAsync(string title) {
            return base.Channel.CheckoutBookAsync(title);
        }
    }
}
